apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: clidemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clidemo 
    spec:
      containers:
        - name: clidemo 
          image: gosampleappb39a.azurecr.io/clidemo 
          ports:
          - containerPort: 3000